### ISSUE TITLE
[BUG?] After enable the plugin, it disappeared from config panel with a error message

### ISSUE THREAD

**Issue by Quorafind** [elias-sundqvist/obsidian-static-file-server#1]
![image](https://user-images.githubusercontent.com/13215013/120731015-49ea2980-c515-11eb-84a8-f2fbcfcfc656.png)

And the error message is

![image](https://user-images.githubusercontent.com/13215013/120731114-7ef67c00-c515-11eb-9335-0a5ac4f8f1d9.png)

I have tried twice to reinstall it and reenable it.

**Comment by elias-sundqvist** [comment]
Is this your first time trying to use the plugin, or have you used it successfully before?
From the error message, it looks like you have mapped the port "." (which is invalid) to some directory. 
I'm a bit surprised by this since I already validate the ports before they are saved.

Anyways, I have added some additional port validation now, so hopefully the plugin won't crash for you anymore.

**Comment by Quorafind** [comment]
It works perfectly now , Thanks for your hard job. Closed
